---
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
Year <- factor(2017:2022)
World <- c(3349, 3109, 2960, 2383, 2219, 1614)
Country <- c(6, 6, 6, 5, 4, 2)
label <- c("World rank - 3349" "Country rank - 6",
           "World rank - 3109" "Country rank - 6",
           "World rank - 2960" "Country rank - 6",
           "World rank - 2383" "Country rank - 5",
           "World rank - 2219" "Country rank - 4",
           "World rank - 1614" "Country rank - 2")
clabel <- c("Country rank - 6",
           "Country rank - 6",
           "Country rank - 6",
           "Country rank - 5",
           "Country rank - 4",
           "Country rank - 2")

df <- data.frame(Year, World, Country, label, clabel)
df


library(ggplot2)
library(gganimate)
ggplot(df, aes(x = Year, y = World)) +  # Plot with values on top
  geom_bar(stat = "identity", fill= "#800026") + coord_flip() +
  geom_text(aes(label = clabel), size=5,
            vjust = -0.2, colour = "#fed976") +
  scale_x_discrete(labels = Year) + 
  theme_minimal() + 
  ylab("Webometrics Ranking")  

ggplot(df, aes(x = Year, y = World)) +  # Plot with values on top
  geom_bar(stat = "identity", fill= "#800026") + coord_flip() +
  geom_text(aes(label = clabel), size=5,
            vjust = -0.2, colour = "#fed976") +
  scale_x_discrete(labels = Year) + 
  theme_minimal() + 
  ylab("Webometrics Ranking")  
  


plot2 <- ggplot(df, aes(x = Year, y = World)) +  # Plot with values on top
  geom_bar(stat = "identity", fill= "#800026") + coord_flip() +
  geom_text(aes(label = clabel), size=5,
            vjust = -0.2, colour = "#fed976") +
  scale_x_discrete(labels = Year) + 
  theme_minimal() + 
  ylab("Webometrics Ranking") + 
  transition_time(as.integer(Year)) +
  shadow_mark() +
  enter_grow() +
  enter_fade()

mygif <- animate(plot2, width=1600, height=800, renderer=gifski_renderer(loop=FALSE))  
mygif
anim_save(filename="animation.gif", mygif)


```